development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://comp205p-faye.com/faye"
  secret_token: "c69bebba91cffe416a22706c12666ec2dfaf38e9e6bac112c3b6e5f8c8a095bd"
  signature_expiration: 3600 # one hour
